abstract final class RouteNames {
  static const splash = 'splash';
  static const login = 'login';
  static const register = 'register';
  static const home = 'home';
  static const profile = 'profile';
  static const profileEdit = 'profile-edit';
  static const motorcycles = 'motorcycles';
  static const motorcycleCreate = 'motorcycle-create';
  static const motorcycleDetail = 'motorcycle-detail';
  static const motorcycleEdit = 'motorcycle-edit';
  static const marketplace = 'marketplace';
  static const marketplaceProductDetail = 'marketplace-product-detail';
  static const marketplaceCreate = 'marketplace-create';
  static const marketplaceProductEdit = 'marketplace-product-edit';
  static const marketplaceProductImages = 'marketplace-product-images';
  static const myProducts = 'my-products';
  static const favorites = 'favorites';
  static const workshops = 'workshops';
  static const workshopDetail = 'workshop-detail';
  static const theftReports = 'theft-reports';
  static const theftReportDetail = 'theft-report-detail';
  static const myTheftReports = 'my-theft-reports';
  static const theftReportCreate = 'theft-report-create';
}