import 'package:flutter/material.dart';

abstract final class AppLocalizations {
  static const localeName = 'es';

  static const appName = 'MotoHub';
  static const login = 'Iniciar sesión';
  static const register = 'Crear cuenta';
  static const logout = 'Cerrar sesión';
  static const homeWelcome = 'Bienvenido a MotoHub';
  static const manageProductImages = 'Imágenes del producto';
  static const addImages = 'Agregar imágenes';
  static const uploadImages = 'Subir imágenes';
  static const uploadingImage = 'Subiendo';
  static const imagePrimary = 'Principal';
  static const setAsPrimary = 'Establecer como principal';
  static const deleteImage = 'Eliminar';
  static const confirmDeleteImage = '¿Eliminar esta imagen?';
  static const skipImages = 'Omitir';
  static const finish = 'Finalizar';
  static const maxImagesReached = 'Se alcanzó el máximo de imágenes.';
  static const invalidImage = 'Usa JPG, PNG o WebP de hasta 5 MB.';
  static const uploadFailed = 'No se pudo subir la imagen.';
  static const retry = 'Reintentar';
  static const syncWarning = 'La operación se completó, pero no se pudo actualizar la información.';
  static const cancel = 'Cancelar';
  static const readOnlyImages = 'Las imágenes se muestran en modo lectura.';
  static const uploadedImages = 'Imágenes subidas';
  static const noImages = 'No hay imágenes.';
  static const pendingSelection = 'Selección pendiente';
  static const imageError = 'Error';
  static const uploading = 'Subiendo...';
  static const removeImage = 'Quitar';
  static const workshops = 'Talleres';
  static const notifications = 'Notificaciones';
  static const conversations = 'Conversaciones';
  static const chat = 'Chat';
  static const defaultUser = 'Usuario';
  static const chatConnecting = 'Conectando...';
  static const chatReconnecting = 'Reconectando...';
  static const chatOffline = 'Sin conexión';
  static const noConversations = 'No tienes conversaciones.';
  static const noMessages = 'No hay mensajes todavía.';
  static const writeMessage = 'Escribe un mensaje';
  static const send = 'Enviar';
  static const newConversation = 'Nueva conversación';
  static const recipientUserId = 'Id del destinatario';
  static const open = 'Abrir';
  static const noNotifications = 'No tienes notificaciones.';
  static const markAllAsRead = 'Marcar todas como leídas';
  static const unread = 'No leídas';
  static const notificationLoadFailed = 'No se pudieron cargar las notificaciones.';
  static const notificationMarkReadFailed = 'No se pudo marcar la notificación como leída.';
  static const notificationMarkAllReadFailed = 'No se pudieron marcar todas las notificaciones como leídas.';
  static const unknownNotification = 'Notificación';
  static const dismiss = 'Cerrar';
  static const searchWorkshops = 'Buscar talleres';
  static const city = 'Ciudad';
  static const clearCity = 'Limpiar ciudad';
  static const noWorkshops = 'No hay talleres disponibles.';
  static const workshopDetail = 'Detalle del taller';
  static const services = 'Servicios';
  static const schedule = 'Horario';
  static const reviews = 'Reseñas';
  static const noReviews = 'Sin reseñas';
  static const rating = 'Valoración';
  static const reviewCount = 'reseñas';
  static const locationUnavailable = 'Ubicación no disponible';
  static const coordinates = 'Coordenadas';
  static const closed = 'Cerrado';
  static const loadMore = 'Cargar más';
  static const noServices = 'No hay servicios disponibles.';
  static const noSchedule = 'No hay horario disponible.';
  static const phone = 'Teléfono';
  static const email = 'Correo';
  static const address = 'Dirección';
  static const description = 'Descripción';
  static const contact = 'Contacto';
  static const sunday = 'Domingo';
  static const monday = 'Lunes';
  static const tuesday = 'Martes';
  static const wednesday = 'Miércoles';
  static const thursday = 'Jueves';
  static const friday = 'Viernes';
  static const saturday = 'Sábado';
  static const minutes = 'min';
  static const listView = 'Lista';
  static const mapView = 'Mapa';
  static const workshopsViewMode = 'Modo de vista de talleres';
  static const noWorkshopsWithLocation = 'No hay talleres con ubicación disponible.';

  static String communityTitle(Locale locale) => locale.languageCode == 'en' ? 'Community' : 'Comunidad';
  static String communityCreate(Locale locale) => locale.languageCode == 'en' ? 'New post' : 'Nueva publicación';
  static String communityContentHint(Locale locale) => locale.languageCode == 'en' ? 'What do you want to share?' : '¿Qué quieres compartir?';
  static String communityPublish(Locale locale) => locale.languageCode == 'en' ? 'Publish' : 'Publicar';
  static String communityDelete(Locale locale) => locale.languageCode == 'en' ? 'Delete post' : 'Eliminar publicación';
  static String communityDeleteConfirmation(Locale locale) => locale.languageCode == 'en' ? 'This action will delete the post.' : 'Esta acción eliminará la publicación.';
  static String communityCancel(Locale locale) => locale.languageCode == 'en' ? 'Cancel' : 'Cancelar';
  static String communityDeleteAction(Locale locale) => locale.languageCode == 'en' ? 'Delete' : 'Eliminar';
  static String communityEmpty(Locale locale) => locale.languageCode == 'en' ? 'No posts yet.' : 'Sin publicaciones.';
  static String communityLoadFailed(Locale locale) => locale.languageCode == 'en' ? 'Community could not be loaded.' : 'No se pudo cargar la comunidad.';
  static String communityPublishFailed(Locale locale) => locale.languageCode == 'en' ? 'The post could not be published.' : 'No se pudo publicar.';
  static String communityDeleteFailed(Locale locale) => locale.languageCode == 'en' ? 'The post could not be deleted.' : 'No se pudo eliminar.';
  static String communityCharacterCount(Locale locale, int current, int max) => locale.languageCode == 'en' ? '$current / $max' : '$current / $max';
  static String communityComments(Locale locale) => locale.languageCode == 'en' ? 'comments' : 'comentarios';
  static String communityLikes(Locale locale) => locale.languageCode == 'en' ? 'likes' : 'me gusta';
  static String communityDetail(Locale locale) => locale.languageCode == 'en' ? 'Post' : 'Publicación';
  static String communityLike(Locale locale) => locale.languageCode == 'en' ? 'Like' : 'Me gusta';
  static String communityUnlike(Locale locale) => locale.languageCode == 'en' ? 'Unlike' : 'Quitar me gusta';
  static String communityCommentsTitle(Locale locale) => locale.languageCode == 'en' ? 'Comments' : 'Comentarios';
  static String communityCommentHint(Locale locale) => locale.languageCode == 'en' ? 'Write a comment' : 'Escribe un comentario';
  static String communitySendComment(Locale locale) => locale.languageCode == 'en' ? 'Send comment' : 'Enviar comentario';
  static String communityDeleteComment(Locale locale) => locale.languageCode == 'en' ? 'Delete comment' : 'Eliminar comentario';
  static String communityDeleteCommentConfirmation(Locale locale) => locale.languageCode == 'en' ? 'This comment will be deleted.' : 'Este comentario se eliminará.';
  static String communityNoComments(Locale locale) => locale.languageCode == 'en' ? 'No comments yet.' : 'Aún no hay comentarios.';
  static String communityUnavailable(Locale locale) => locale.languageCode == 'en' ? 'Post unavailable.' : 'Publicación no disponible.';
  static String communityRetry(Locale locale) => locale.languageCode == 'en' ? 'Retry' : 'Reintentar';
  static String communityCommentRequired(Locale locale) => locale.languageCode == 'en' ? 'Comment is required.' : 'El comentario es obligatorio.';
  static String communityCommentTooLong(Locale locale) => locale.languageCode == 'en' ? 'Comment must be at most 2000 characters.' : 'El comentario debe tener como máximo 2000 caracteres.';
  static String newsTitle(Locale locale) => locale.languageCode == 'en' ? 'News' : 'Noticias';
  static String newsAll(Locale locale) => locale.languageCode == 'en' ? 'All' : 'Todas';
  static String newsCategories(Locale locale) => locale.languageCode == 'en' ? 'Categories' : 'Categorías';
  static String newsEmpty(Locale locale) => locale.languageCode == 'en' ? 'No news available.' : 'No hay noticias disponibles.';
  static String newsLoadFailed(Locale locale) => locale.languageCode == 'en' ? 'News could not be loaded.' : 'No se pudieron cargar las noticias.';
  static String newsCategoriesLoadFailed(Locale locale) => locale.languageCode == 'en' ? 'Categories could not be loaded.' : 'No se pudieron cargar las categorías.';
  static String newsRetry(Locale locale) => locale.languageCode == 'en' ? 'Retry' : 'Reintentar';
  static String newsLoadMore(Locale locale) => locale.languageCode == 'en' ? 'Load more' : 'Cargar más';
  static String newsImageUnavailable(Locale locale) => locale.languageCode == 'en' ? 'Image unavailable' : 'Imagen no disponible';
  static String newsDetailTitle(Locale locale) => locale.languageCode == 'en' ? 'News detail' : 'Detalle de noticia';
  static String newsDetailLoadFailed(Locale locale) => locale.languageCode == 'en' ? 'News could not be loaded.' : 'No se pudo cargar la noticia.';
  static String newsNotFound(Locale locale) => locale.languageCode == 'en' ? 'News could not be found.' : 'No se pudo encontrar la noticia.';
  static String newsSummary(Locale locale) => locale.languageCode == 'en' ? 'Summary' : 'Resumen';
  static String newsContent(Locale locale) => locale.languageCode == 'en' ? 'Content' : 'Contenido';
}
